server:
  port: 8001
  servlet:
    context-path: /member

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: member

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    org:
      clone:
        member:
          mapper: trace