server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: http://127.0.0.1:8001
        - id: business
          predicates:
            - Path=/business/**
          uri: http://127.0.0.1:8002
        - id: batch
          predicates:
            - Path=/batch/**
          uri: http://127.0.0.1:8003
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true #允许携带cookie
            allowedHeaders: '*' #允许携带的头信息
            allowedMethods: '*' #允许的请求方式
            allowedOriginPatterns: '*' #允许请求来源
            maxAge: 3600 #跨域检测有效期