server:
  port: 8002
  servlet:
    context-path: /business

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    org:
      clone:
        business:
          mapper: trace